language: node_js
node_js:
  - '10.15.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 # circle ci dependencies
  - npm install
before_deploy:
  - npm run prod
  - npm install -g firebase-tools
deploy:
  provider: firebase
  skip-cleanup: true
  token:
    secure: "C6xDqVTeUixAH2dac3czdUTHOM9zPlLY1HXrggP7uOKGyb7Sc72V8zqrbMT8KvJjFbqib5RqFdmSsPii+hrcLqvzdAgcu6dWrF+8XJCQA2+UzyNhdKiyVwtpp/zfx0x5upLw2SQCiuVmzgj6IlvWYUlcBZs+7TldDmesk6TCSD/c2nfgwdO1VTsfvdCfNXNDzE8qsDZq1Xjv9+utJ2SLbikbWS8z6TeQwlesHgrt9cdo2kl/Eixu3ji5E/pOdU5VNxR9skHNWSjHNkG2eXAkLNhMXdIZr+GKf+vzylljJWKzPn18+ev26AwLl5j+jKHYQxLtO5pF2eTO90jkFLbtB7eDqFCMEQIOyflQYT1wFsysogeyARRah2f/yCGyAgZnTehl2G2XFw1yH0y5Cc4oJmV5eVqOWaR47rPrpdgiecayi3kYE6daci7vVE+jnAlVM1n51hGprZD3MTO0fxiVEPxvCAXnFFcpaNU1ldZ6Q82Q+td+tTp+hcjm+tFTicBA2yXenbhpxXzFg2zGRw6c+08+MZY+5ed+5OE9cy2cuNW7jATrV5u5i7cFss9+fP0hfvKTDefysI4dqw4NupmoF260MU4njxStLYJc9Kj9zBPOZDF3K2Vs9Qx9VQD8JuZ3xA2Lvu7dWptDNT0NfeBP6AwMt6cEwQSRTTJLwnmSMU4="
  local-dir: dist
  on:
    branch: master